from django.urls import path
from projectM import views

app_name = 'projectM'

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('resume', views.resume, name='resume'),
    path('portfolio', views.portfolio, name='portfolio'),
    path('contact', views.contact, name='contact'),
    path('test', views.test, name='test'),
    path('solar_system_explorer', views.solar_system_explorer, name='solar_system_explorer'),
    path('services/resume_builder/<slug:slug>', views.resume_builder, name='resume_builder'),
    path('services/create_resume/<slug:slug>', views.create_resume, name='create_resume'),
    path('services/view_resume/<slug:slug>', views.view_resume, name='view_resume'),
    path('services/chatbot/<slug:slug>/', views.chatbot, name='chatbot'),
    path('services/library_management/<slug:slug>/', views.library_management, name='library_management'),
    path('library_management/manage_library_card', views.manage_library_card, name='manage_library_card'),
    path('library_management/add_book', views.add_book, name='add_book'),
    path('library_management/view_books', views.view_books, name='view_books'),
    path('library_management/edit_book/<int:book_id>', views.edit_book, name = 'edit_book'),
    path('library_management/delete_book/<int:book_id>', views.delete_book, name = 'delete_book'),
    path('library_management/borrow_book', views.borrow_book, name = 'borrow_book'),
    path('library_management/return_book', views.return_book, name='return_book'),
    path('library_management/add_admin', views.add_admin, name='add_admin'),
    path('services/weather_app/<slug:slug>/', views.weather_app, name='weather_app'),
    path('services/expense_tracker/<slug:slug>/', views.expense_tracker, name='expense_tracker'),
    path('expense_tracker/add_expense', views.add_expense, name='add_expense'),
    path('services/to_do_list/<slug:slug>/', views.to_do_list, name='to_do_list'),
    path('complete_task/<slug:slug>/<int:task_id>', views.complete_task, name='complete_task'),
    path('delete_task/<slug:slug>/<int:task_id>', views.delete_task, name='delete_task'),
    path('services/contact_manager/<slug:slug>/', views.contact_manager, name='contact_manager'),
    path('contact_manager/add_contact', views.add_contact, name='add_contact'),
    path('contact_manager/edit_contact/<int:contact_id>', views.edit_contact, name='edit_contact'),
    path('contact_manager/delete_contact/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('services/job_board/<slug:slug>', views.job_board, name='job_board'),
    path('job_board/post_job', views.post_job, name='post_job'),
    path('job_board/apply_job', views.apply_job, name='apply_job'),
    path('services/online_polling_system/<slug:slug>', views.online_polling_system, name='online_polling_system'),
    path('online_polling_system/create_poll', views.create_poll, name = 'create_poll'),
    path('online_polling_system/vote_poll/<int:poll_id>', views.vote_poll, name = 'vote_poll'),
    path('online_polling_system/polls_result/<int:poll_id>', views.polls_result, name='polls_result'),
    path('online_polling_system/activate_poll/<int:poll_id>', views.activate_poll, name='activate_poll'),
    path('online_polling_system/deactivate_poll/<int:poll_id>', views.deactivate_poll, name='deactivate_poll'),
    path('services/quiz_app/<slug:slug>', views.quiz_app, name='quiz_app'),
    path('quiz_app/quiz_list', views.quiz_list, name='quiz_list'),
    path('quiz_app/add_quiz', views.add_quiz, name='add_quiz'),
    path('quiz_app/manage_quiz', views.manage_quiz, name='manage_quiz'),
    path('quiz_app/view_participants', views.view_participants, name='view_participants'),
    path('quiz_app/quiz_results/<int:quiz_id>', views.quiz_results, name='quiz_results'),
    path('quiz_app/quiz/<int:quiz_id>/<int:question_id>', views.quiz, name='quiz'),
    path('quiz_app/leaderboard/<int:quiz_id>', views.leaderboard, name='leaderboard'),
    path('quiz_app/add_quiz_details', views.add_quiz_details, name='add_quiz_details'),
   ]

