# Generated by Django 5.2.1 on 2025-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='birthday',
            field=models.DateField(),
        ),
    ]
