# Generated by Django 5.2.1 on 2025-06-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0002_alter_about_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
