# Generated by Django 5.2.1 on 2025-06-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
