# Generated by Django 5.2.1 on 2025-06-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0005_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon_color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
