# Generated by Django 5.2.1 on 2025-06-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0006_services_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
