# Generated by Django 5.2.1 on 2025-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0007_services_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(null=True, upload_to='resume/profile_photos')),
                ('address', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('education', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('objective', models.TextField()),
                ('work_experience', models.TextField()),
                ('skills', models.TextField()),
                ('certifications', models.TextField()),
                ('projects', models.TextField()),
            ],
        ),
    ]
