# Generated by Django 5.2.1 on 2025-06-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0009_resume_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('response', models.TextField()),
            ],
        ),
    ]
