# Generated by Django 5.2.1 on 2025-06-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0010_chatbotrules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageLibraryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('issue_date', models.DateField()),
            ],
        ),
    ]
