# Generated by Django 5.2.1 on 2025-06-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0011_managelibrarycard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managelibrarycard',
            name='card_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
