# Generated by Django 5.2.1 on 2025-06-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0012_alter_managelibrarycard_card_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managelibrarycard',
            old_name='issue_date',
            new_name='issued_date',
        ),
    ]
