# Generated by Django 5.2.1 on 2025-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0013_rename_issue_date_managelibrarycard_issued_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
