# Generated by Django 5.2.1 on 2025-06-12 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0014_addbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addbook',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addbook',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
