# Generated by Django 5.2.1 on 2025-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0015_addbook_borrowed_addbook_borrowed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
