# Generated by Django 5.2.1 on 2025-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0017_expensecategory_expensestracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
