# Generated by Django 5.2.1 on 2025-06-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0020_jobtype_jobboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboard',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobboard',
            name='requirements',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobboard',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
