# Generated by Django 5.2.1 on 2025-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0021_jobboard_email_jobboard_requirements_jobboard_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='job_board/job_applications/resumes')),
                ('cover_letter', models.TextField()),
            ],
        ),
    ]
