# Generated by Django 5.2.1 on 2025-07-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0023_alter_jobapplications_resume_onlinepollingsystem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepollingsystem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onlinepollingsystem',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
