# Generated by Django 5.2.1 on 2025-07-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0028_quizdetails_number_of_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizdetails',
            name='number_of_questions',
        ),
    ]
