# Generated by Django 5.2.1 on 2025-07-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0029_remove_quizdetails_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
