# Generated by Django 5.2.1 on 2025-07-10 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0030_useranswer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='projectM.quizdetails'),
        ),
    ]
