# Generated by Django 5.2.1 on 2025-07-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectM', '0031_alter_useranswer_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='quiz',
            new_name='quiz_detail',
        ),
    ]
